### ISSUE TITLE
Crash after navigation comes to finish marker

### ISSUE THREAD

**Issue by samvgorode** [mapbox/mapbox-navigation-android#150]
I have a crash when navigation finishes. How to finish it correctly? In onRunning I do the next if is not running: 
```
if(navigationMapRoute.getRoute()!=null)navigationMapRoute.removeRoute();
if(destinationMarker!=null)destinationMarker.remove();
```
And have a crash:
```
E/UncaughtException: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                                        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                        at java.util.ArrayList.get(ArrayList.java:308)
                                                                        at com.mapbox.services.android.navigation.v5.DefaultMilestones$2.buildInstruction(DefaultMilestones.java:67)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationEngine.buildInstructionString(NavigationEngine.java:129)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:104)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationService.forceLocationUpdate(NavigationService.java:168)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationService.startRoute(NavigationService.java:156)
                                                                        at com.mapbox.services.android.navigation.v5.MapboxNavigation$NavigationServiceConnection.onServiceConnected(MapboxNavigation.java:485)
                                                                        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1335)
                                                                        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1352)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: no.sammevei.app, PID: 30127
                                                                 java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                                     at com.mapbox.services.android.navigation.v5.DefaultMilestones$2.buildInstruction(DefaultMilestones.java:67)
                                                                     at com.mapbox.services.android.navigation.v5.NavigationEngine.buildInstructionString(NavigationEngine.java:129)
                                                                     at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:104)
                                                                     at com.mapbox.services.android.navigation.v5.NavigationService.forceLocationUpdate(NavigationService.java:168)
                                                                     at com.mapbox.services.android.navigation.v5.NavigationService.startRoute(NavigationService.java:156)
                                                                     at com.mapbox.services.android.navigation.v5.MapboxNavigation$NavigationServiceConnection.onServiceConnected(MapboxNavigation.java:485)
                                                                     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1335)
                                                                     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1352)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by cammace** [comment]
> Invalid index 2, size is 2

It is an issue with the default milestones trying to get a null upcoming route. https://github.com/mapbox/mapbox-navigation-android/pull/145 should have fixed the issue and _will_ be in the 0.4.0 release. Sorry about this fellas.

**Comment by Grsmto** [comment]
I just updated to 0.4.0 and the issue seems to persist.

**Comment by Grsmto** [comment]
I fixed that specific issue but ended up with another one:

```
08-14 16:19:21.341 19497-19623/com.mapbox.services.android.navigation.testapp E/AndroidRuntime: FATAL EXCEPTION: NavThread
                                                                                                Process: com.mapbox.services.android.navigation.testapp, PID: 19497
                                                                                                java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                                                                                                    at java.util.ArrayList.get(ArrayList.java:411)
                                                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.nextManeuverPosition(NavigationHelper.java:202)
                                                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.stepDistanceRemaining(NavigationHelper.java:75)
                                                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.generateNewRouteProgress(NavigationEngine.java:110)
                                                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleRequest(NavigationEngine.java:64)
                                                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleMessage(NavigationEngine.java:59)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
```

`return coords.size() > 1 ? coords.get(coords.size() - 1) : coords.get(coords.size());``

This line of code breaks if `coordsSize()` is 1 as it will try to do `coords.get(1)` which is null.
It should be:
`return coords.size() >= 1 ? coords.get(coords.size() - 1) : coords.get(coords.size());`


I probably send a PR for this.

**Comment by cammace** [comment]
Thanks to @Grsmto for the fix in https://github.com/mapbox/mapbox-navigation-android/pull/175, we should be good here, closing but will reopen if you guys are seeing the issue still.

**Comment by samvgorode** [comment]
finishing the navigation still crashes for me, what navigation version is relevant? 
```
E/UncaughtException: java.lang.IndexOutOfBoundsException: setSpan (2 ... 2) ends beyond length 0
                                                                      at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
                                                                      at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
                                                                      at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
                                                                      at android.text.Selection.setSelection(Selection.java:76)
                                                                      at android.widget.EditText.setSelection(EditText.java:91)
                                                                      at android.widget.NumberPicker$SetSelectionCommand.run(NumberPicker.java:2246)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: no.sammevei.app, PID: 1723
                                                               java.lang.IndexOutOfBoundsException: setSpan (2 ... 2) ends beyond length 0
                                                                   at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
                                                                   at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
                                                                   at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
                                                                   at android.text.Selection.setSelection(Selection.java:76)
                                                                   at android.widget.EditText.setSelection(EditText.java:91)
                                                                   at android.widget.NumberPicker$SetSelectionCommand.run(NumberPicker.java:2246)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by samvgorode** [comment]
today, when I have 6 meters before finish marker. 0.5.0-SNAPSHOT.
```
E/UncaughtException: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                                        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                        at java.util.ArrayList.get(ArrayList.java:308)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.DefaultMilestones$2.buildInstruction(DefaultMilestones.java:59)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.buildInstructionString(NavigationHelper.java:61)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onMilestoneTrigger(NavigationService.java:197)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:79)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by Grsmto** [comment]
Hey @samvgorode if you want I got a fork with a fix for this https://github.com/Grsmto/mapbox-navigation-android/tree/grsmto-fix-app-crash-end-nav?files=1
This bug is awaiting for cammace to rework my own fix.

**Comment by samvgorode** [comment]
I appreciate your work, but, please, let me know when it will be fixed сompletely.

**Comment by rektph** [comment]
is there a fix for this?

` E/AndroidRuntime: FATAL EXCEPTION: NavThread
                                                                         Process: com.froura.develo4.driver, PID: 4516
                                                                         java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
                                                                             at java.util.ArrayList.get(ArrayList.java:411)
                                                                             at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.decodeStepPoints(NavigationEngine.java:255)
                                                                             at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.advanceStepIndex(NavigationEngine.java:227)
                                                                             at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.buildNewRouteProgress(NavigationEngine.java:161)
                                                                             at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleRequest(NavigationEngine.java:96)
                                                                             at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleMessage(NavigationEngine.java:62)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)`
