### ISSUE TITLE
Route not properly centered after clicking on route preview button

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1718]
The route is not properly centered after clicking on the route preview button in both landscape and portrait 👀

![route_preview_not_centered_properly_plus_lifecycle_issue_drawing_previous_route](https://user-images.githubusercontent.com/1668582/52143487-96fa2000-2629-11e9-85fd-43ce7b5e7adf.gif)

Apparently the camera bounds are still relying on the `origin`. Noting that I was re-routed a couple of times before route preview button was clicked.

Also if you see the video carefully there's some lifecycle issue because when rotating the first time to landscape the previous route gets displayed and it kept displaying even after rotating to portrait.

This seems kind of similar to https://github.com/mapbox/mapbox-navigation-android/issues/1673#event-2083171685 and the changes introduced in https://github.com/mapbox/mapbox-navigation-android/pull/1688 could be related.

**Comment by danesfeder** [comment]
The `Geometry` passed through `RouteProgress` in #1895 will help provide fresh data in `DynamicCamera` to hopefully address this ticket.

**Comment by Guardiola31337** [comment]
@abhishek1508 it'd be great to fix this in the `1.0` UI SDK.

**Comment by abhishek1508** [comment]
Let's verify/fix.
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
It looks like this issue has been resolved. When testing I see the route centered in the screen in both landscape and portrait modes.

![20200723_101709](https://user-images.githubusercontent.com/2249818/88317235-d610ab00-cccd-11ea-8dc6-3a87f28f39ec.gif)

![20200723_101811](https://user-images.githubusercontent.com/2249818/88317330-f93b5a80-cccd-11ea-90ed-22481ac9d013.gif)

**Comment by Guardiola31337** [comment]
@cafesilencio have we tested 👇 too?

> Noting that I was re-routed a couple of times before route preview button was clicked.

I'd swear this is still an issue as we didn't change any `DynamicCamera` logic 🤔 

Could we verify 🙏?

**Comment by cafesilencio** [comment]
I retested with SummaryBottomSheetActivity and used a mock location app to force several reroutes.  After each reroute I clicked the route preview button and the current route was always centered in the screen.
