### ISSUE TITLE
IllegalArgumentException when simulating a route

### ISSUE THREAD

**Issue by 113408** [mapbox/mapbox-navigation-android#2019]
Hi Mapbox team, I'm having a strange bug using the`NavigationView`, I generate a route then pass the route to the `NavigationViewOptions.Builder` and displays it on the `NavigationView`, everything works fine until I set the `shouldSimulateRoute` to true for the builder. It crashes every time with the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pro.mobile4.vision, PID: 20109
    java.lang.IllegalArgumentException: Non-null and non-empty location list required.
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayLocationDispatcher.checkValidInput(ReplayLocationDispatcher.java:79)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayLocationDispatcher.<init>(ReplayLocationDispatcher.java:22)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.obtainDispatcher(ReplayRouteLocationEngine.java:164)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.start(ReplayRouteLocationEngine.java:154)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.beginReplayWith(ReplayRouteLocationEngine.java:203)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.requestLocationUpdates(ReplayRouteLocationEngine.java:113)
        at com.mapbox.services.android.navigation.v5.navigation.LocationUpdater.requestInitialLocationUpdates(LocationUpdater.java:58)
        at com.mapbox.services.android.navigation.v5.navigation.LocationUpdater.<init>(LocationUpdater.java:31)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initializeLocationUpdater(NavigationService.java:124)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initialize(NavigationService.java:95)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.startNavigation(NavigationService.java:66)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.onServiceConnected(MapboxNavigation.java:810)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1848)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1880)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

My code to start the navigation is as follow:
```
private fun startNavigation() {
        val options = NavigationViewOptions.builder()
            .directionsRoute(directionsRoute)
            .navigationListener(this@NavigationFragment)
            .progressChangeListener(this@NavigationFragment)
            .shouldSimulateRoute(true)
            .build()

        navigationView.startNavigation(options)
        navigationView.findViewById<View>(R.id.feedbackFab).visibility = View.GONE
        navigationView.findViewById<View>(R.id.alertView).visibility = View.GONE
    }
```
When I debug a little bit I found that the ReplayRoute gets an empty array of points even though the navigation has all the necessary point.

I tried passing the route to the `ReplayRouteLocationEngine` and then pass the engine to the builder but still getting the same issue.

**Android API:** 28
**Mapbox Navigation SDK version:** 0.41.0

**Comment by schimini** [comment]
@113408 Hi, I've been struggling with the same issue for a while now. Did you tested the app without `shouldSimulateRoute` ?

**Comment by 113408** [comment]
I managed to make it work by using a route without waypoints (just a start
and finish point) not very convenient but didn't have time to dig deeper

**Comment by AlexStroia** [comment]
Happened to me also ! :( Does anyone have a fix for this ?

**Comment by AlexStroia** [comment]
In my case, this problem occurred because one of the waypoints had invalid coordinates.

**Comment by schimini** [comment]
I'm hoping this pr #2066 solves it

**Comment by 113408** [comment]
let's wait for official update from @Guardiola31337  or @andrlee

**Comment by InesRodriguezAlonso** [comment]
I got same error when the origin and destination have the same coordinates. Is there any news?

**Comment by jkpatel1463** [comment]
> I got same error when the origin and destination have the same coordinates. Is there any news?

@InesRodriguezAlonso No, i didn't get any news from Mapbox for this issues in android app.

We don't have such issue in iPhone. Only Android app with Mapbox is crashing for such scenario.

**Comment by Guardiola31337** [comment]
Hey 👋 @113408 @schimini @AlexStroia @jkpatel1463 @InesRodriguezAlonso thanks for checking out the SDK.

Closing here in favor of https://github.com/mapbox/mapbox-navigation-android/issues/3013

In any case, `ReplayRouteLocationEngine` is going to be deprecated and replaced by `ReplayLocationEngine` 👀 https://github.com/mapbox/mapbox-navigation-android/pull/300 which will be available in the upcoming `1.0` public beta release 🚀 Stay tuned!

cc @kmadsen

**Comment by Guardiola31337** [comment]
Hey @113408 @schimini @AlexStroia @jkpatel1463 @InesRodriguezAlonso we've just released [`release_core_1.0.0-rc.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_core_1.0.0-rc.1) 🎉 🚀 

Please review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android and if you already use an older version of the Navigation SDK, check out [the migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" core Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues and please open tickets in https://github.com/mapbox/mapbox-navigation-android/issues/new and we will take it from there! We would love your feedback.

Thanks again!

**Comment by vidhi1011** [comment]
@Guardiola31337 Still getting this crash in new latest versions
I am using navigation view 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'

```
Process: com.flashmarket.delivery, PID: 2437
    java.lang.IllegalArgumentException: Non-null and non-empty location list required.
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayLocationDispatcher.checkValidInput(ReplayLocationDispatcher.java:79)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayLocationDispatcher.<init>(ReplayLocationDispatcher.java:22)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.obtainDispatcher(ReplayRouteLocationEngine.java:164)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.start(ReplayRouteLocationEngine.java:154)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.beginReplayWith(ReplayRouteLocationEngine.java:203)
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.requestLocationUpdates(ReplayRouteLocationEngine.java:113)
        at com.mapbox.services.android.navigation.v5.navigation.LocationUpdater.requestInitialLocationUpdates(LocationUpdater.java:58)
        at com.mapbox.services.android.navigation.v5.navigation.LocationUpdater.<init>(LocationUpdater.java:31)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initializeLocationUpdater(NavigationService.java:124)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initialize(NavigationService.java:95)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.startNavigation(NavigationService.java:66)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.onServiceConnected(MapboxNavigation.java:813)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2037)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2069)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

```

**Comment by kmadsen** [comment]
@vidhi1011 the ReplayRouteLocationEngine is deprecated. Are you able to migrate to the new MapboxReplayer and ReplayLocationEngine?

https://github.com/mapbox/mapbox-navigation-android/issues/2019#issuecomment-638465362
