### ISSUE TITLE
Drop-in UI: LocationLayer below instruction

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#254]
Hey,

I've downloaded your [sample project](https://github.com/mapbox/mapbox-navigation-android/tree/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity) today.

Running on a Google Nexus 6 the Navigation View (Drop-in UI) looks like this:

![2017-09-21 14 20 04](https://user-images.githubusercontent.com/23097192/30695351-2db0c3b2-9ed8-11e7-8773-3807d98f41ed.jpg)

I have not done any gestures.

Best regards,
Patrick

**Comment by danesfeder** [comment]
Hey @P-Zenker, 

Thanks for your feedback - I'll try to get my hands on a physical Nexus 6. 

Running in a Nexus 6 emulator, the navigation puck position seems to be located okay.  Looks like this may not be the case with the actual device.

![screen shot 2017-09-21 at 9 30 26 am](https://user-images.githubusercontent.com/8434572/30698393-d4774b90-9eaf-11e7-85c7-176ecf093c79.png)

**Comment by P-Zenker** [comment]
I think my physical Nexus 6 is just a hardship. Two more screenshots:

MOBISTEL Cynus E4 (Android 5.1 | 800 x 480 | 4 Zoll (normal) | 240 (hdpi)) - fine, or maybe a bit too close?
![2017-09-21 16 53 09](https://user-images.githubusercontent.com/23097192/30702482-5db6704c-9eed-11e7-8f20-2e49f3ad5ae3.jpg)

Ulefone Be Touch 2 (Android 5.1 | 1920 x 1080 | 5,5 Zoll (large)) 
![2017-09-21 16 52 26](https://user-images.githubusercontent.com/23097192/30702454-46e31dac-9eed-11e7-9d9a-662c04a76696.jpg)

**Comment by ericrwolfe** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-android/pull/261

**Comment by P-Zenker** [comment]
With 
```
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT'
compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT') {
    transitive = false
}
```
and 

```   
Position origin = Position.fromCoordinates(10.683995, 53.874354);
Position destination = Position.fromCoordinates(10.685889, 53.872006);
NavigationLauncher.startNavigation(this, origin, destination, null, false);
```
I still get the behaviour described above on my Google Nexus 6. What am I doing wrong?

**Comment by danesfeder** [comment]
@P-Zenker Yeah, going to need to work on a better way to fix this based on the screen size / density of the phone - keep an eye on our PRs for a fix incoming

**Comment by P-Zenker** [comment]
Any news about this issue?

**Comment by danesfeder** [comment]
@P-Zenker Does this camera position occur at the beginning of launching the UI?  Does the puck stay under the sheet even when moving (by simulator or actual location updates) or does the puck align correctly once movement begins?

**Comment by P-Zenker** [comment]
@danesfeder 

With my setup 
```
compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT') {
    transitive = true
}
```
and 

```   
Position origin = Position.fromCoordinates(10.683995, 53.874354);
Position destination = Position.fromCoordinates(10.685889, 53.872006);
NavigationLauncher.startNavigation(this, origin, destination, null, false);
```
and a compiled project today:

> Does this camera position occur at the beginning of launching the UI?

Yes

![2017-10-06 16 19 11](https://user-images.githubusercontent.com/23097192/31282198-1cb36ed0-aab2-11e7-9800-37a09fc87935.jpg)

![2017-10-06 16 19 08](https://user-images.githubusercontent.com/23097192/31282197-1c94f784-aab2-11e7-8516-d355059be3c9.jpg)


>  Does the puck stay under the sheet...

Well, I use a Mock Location App. But Mapbox doesn't listen to it (NavigationLauncher.startNavigation and simulateRoute = false). But that is maybe another issue.

With NavigationLauncher.startNavigation and simulateRoute = true I receive this view:

![2017-10-06 16 17 17](https://user-images.githubusercontent.com/23097192/31282113-d7b3c938-aab1-11e7-9e53-99b89fcfa238.jpg)
