### ISSUE TITLE
Building of 'examples' project was failed. Can not resolve related to libnavigator

### ISSUE THREAD

**Issue by DmitriyYakovlev** [mapbox/mapbox-navigation-android#2541]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior
 1.Clone project
 2.Try to install
 
### Expected behavior
Installed ok.

### Actual behavior
Building error

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':examples:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':examples:debugCompileClasspath'.
   > Could not resolve com.mapbox.navigator:mapbox-navigation-native:km-add-bindings-for-sensor-data-SNAPSHOT-1.
     Required by:
         project :examples > project :libnavigator
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:km-add-bindings-for-sensor-data-SNAPSHOT-1.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_private/com/mapbox/navigator/mapbox-navigation-native/km-add-bindings-for-sensor-data-SNAPSHOT-1/mapbox-navigation-native-km-add-bindings-for-sensor-data-SNAPSHOT-1.pom'.
            > Username must not be null!
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:km-add-bindings-for-sensor-data-SNAPSHOT-1.
         > Could not get resource 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/navigator/mapbox-navigation-native/km-add-bindings-for-sensor-data-SNAPSHOT-1/mapbox-navigation-native-km-add-bindings-for-sensor-data-SNAPSHOT-1.pom'.
            > Could not GET 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/navigator/mapbox-navigation-native/km-add-bindings-for-sensor-data-SNAPSHOT-1/mapbox-navigation-native-km-add-bindings-for-sensor-data-SNAPSHOT-1.pom'. Received status code 409 from server:

**Comment by jsong** [comment]
I'm having the same issue as well.

**Comment by caisd1998** [comment]
Same issue.
I can understand that the navigator native is close source, can we download a compiled framework like how iOS does?

**Comment by NikTsy** [comment]
+1 

Building error on example and app branches. 

`
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':examples:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':examples:debugCompileClasspath'.
   > Could not resolve com.mapbox.navigator:mapbox-navigation-native:9.2.1.
     Required by:
         project :examples > project :libnavigator
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:9.2.1.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_private/com/mapbox/navigator/mapbox-navigation-native/9.2.1/mapbox-navigation-native-9.2.1.pom'.
            > Username must not be null!
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:9.2.1.
         > Could not get resource 'https://mapbox.bintray.com/mapbox_collab/com/mapbox/navigator/mapbox-navigation-native/9.2.1/mapbox-navigation-native-9.2.1.pom'.
            > Username must not be null!
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:9.2.1.
         > Could not get resource 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/navigator/mapbox-navigation-native/9.2.1/mapbox-navigation-native-9.2.1.pom'.
            > Could not GET 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/navigator/mapbox-navigation-native/9.2.1/mapbox-navigation-native-9.2.1.pom'. Received status code 409 from server: 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`

**Comment by Guardiola31337** [comment]
This will be solved when releasing `1.0` publicly.

Closing here.

**Comment by weirenren** [comment]
the same problem occur.

**Comment by KayHung** [comment]
I have the same problem.

**Comment by Guardiola31337** [comment]
Hey @DmitriyYakovlev @jsong @NikTsy @weirenren @KayHung 👋 Thanks for checking out the SDK.

We released [`release_core_1.0.0-rc.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/release_core_1.0.0-rc.1) 🎉 🚀 

Please review the [developer documentation](https://docs.mapbox.com/android/beta/navigation/overview/#installation) to start building with the Mapbox core Navigation SDK v1.0 for Android. After adding that setup you should be able to build from source.

Let us know if you run into any issues or if you find something missing in the documentation.

**Comment by peytonwupeixin** [comment]
Hi, I config all(mapbox username,public access token,secret access token,) follow the https://docs.mapbox.com/android/beta/navigation/overview/#installation doc,but still have the error as 

 project :app > project :module_mapbox
      > Could not resolve com.mapbox.navigation:core:1.0.0-rc.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/navigation/core/1.0.0-rc.1/core-1.0.0-rc.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v1/navigation/android/maven/com/mapbox/navigation/core/1.0.0-rc.1/core-1.0.0-rc.1.pom'. Received status code 403 from server: Forbidden

**Comment by KayHung** [comment]
Hi, I use release_core_1.0.0-rc.1 version.
There still have some error as
Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5.
Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.plugin:maps-style:10.0.0-alpha.5.

**Comment by abhishek1508** [comment]
Hi @KayHung @peytonwupeixin 
It would really help us if you could share your `app/build.gradle` and `project/build.gradle` here.
Thanks

**Comment by KayHung** [comment]
app/build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.github.triplet.play'
apply from: "${rootDir}/gradle/script-git-version.gradle"
apply from: "${rootDir}/gradle/ktlint.gradle"

android {
  compileSdkVersion androidVersions.compileSdkVersion
  buildToolsVersion androidVersions.buildToolsVersion

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  playConfigs {
    defaultAccountConfig {
      serviceAccountCredentials = file("$project.rootDir/android-gl-native-15d95ab30d0f.json")
    }
  }

  def getGitHash = { ->
    try {
      def stdout = new ByteArrayOutputStream()
      exec {
        commandLine 'git', 'rev-parse', '--short', 'HEAD'
        standardOutput = stdout
      }
      return stdout.toString().trim()
    } catch (Exception exception) {
      return ""
    }
  }

  defaultConfig {
    applicationId "com.mapbox.services.android.navigation.app"
    minSdkVersion androidVersions.minSdkVersion
    targetSdkVersion androidVersions.targetSdkVersion
    multiDexEnabled true
    versionCode gitVersionCode
    versionName gitVersionName
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    vectorDrawables.useSupportLibrary = true
    buildConfigField "String", "GIT_HASH", "\"${getGitHash()}\""
  }

  signingConfigs {
    release {
      keyAlias System.getenv("CIRCLECI_ANDROID_KEYSTORE_ALIAS")
      keyPassword System.getenv("CIRCLECI_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD")
      storeFile file("$project.rootDir/navigation_testapp.keystore")
      storePassword System.getenv("CIRCLECI_ANDROID_KEYSTORE_PASSWORD")
    }
  }

  buildTypes {
    debug {
      testCoverageEnabled = false
      manifestPlaceholders = [enableCrashReporting:"false"]
    }
    release {
      minifyEnabled true
      signingConfig signingConfigs.release
      manifestPlaceholders = [enableCrashReporting:"true"]
    }
  }

  dexOptions {
    maxProcessCount 8
    javaMaxHeapSize "2g"
    preDexLibraries true
  }

  lintOptions {
    abortOnError false
  }

  play {
    serviceAccountCredentials = playConfigs.defaultAccountConfig.serviceAccountCredentials
    track = System.getenv("GOOGLE_PLAY_TRACK") ?: "internal"
  }
}

dependencies {
  //ktlint
  ktlint dependenciesList.ktlint

  // Kotlin support
  implementation dependenciesList.kotlinStdLib
  implementation dependenciesList.ankoCommon

  // Mapbox Navigation SDK
  implementation project(':libandroid-navigation-ui')
  implementation dependenciesList.mapboxMapSdk
  implementation dependenciesList.mapboxSearchSdk
  implementation dependenciesList.mapboxCrashMonitor

  // Support libraries
  implementation dependenciesList.androidXAppCompat
  implementation dependenciesList.materialDesign
  implementation dependenciesList.androidXRecyclerView
  implementation dependenciesList.androidXConstraintLayout
  implementation dependenciesList.androidXCardView
  implementation dependenciesList.lifecycleExtensions

  implementation dependenciesList.gmsLocation

  implementation dependenciesList.firebaseCore
  implementation dependenciesList.crashlytics

  implementation dependenciesList.multidex

  // Logging
  implementation dependenciesList.timber

  // Network
  implementation(dependenciesList.okhttp) {
    force = true
  }
  implementation(dependenciesList.okhttpInterceptor) {
    force = true
  }

  // Butter Knife
  implementation dependenciesList.butterKnife
  annotationProcessor dependenciesList.butterKnifeProcessor

  // Leak Canary
  debugImplementation dependenciesList.leakCanaryDebug

  // Unit Testing
  testImplementation dependenciesList.junit
  testImplementation dependenciesList.mockito
  testImplementation dependenciesList.mockk

  // Instrumentation testing
  androidTestImplementation dependenciesList.testRules
  androidTestImplementation(dependenciesList.testEspressoCore, {
    exclude group: 'com.android.support', module: 'support-annotations'
  })
  androidTestImplementation dependenciesList.testEspressoContrib
}

apply from: "${rootDir}/gradle/developer-config.gradle"
apply from: "${rootDir}/gradle/checkstyle.gradle"
apply from: "${rootDir}/gradle/dependency-updates.gradle"
```

project/build.gradle

```
apply plugin: 'com.github.kt3k.coveralls'
apply plugin: 'jacoco'

buildscript {
  apply from: "${rootDir}/gradle/dependencies.gradle"
  ext.kotlin_version = '1.3.72'
  repositories {
    google()
    mavenCentral()
    jcenter()
    maven { url 'https://plugins.gradle.org/m2' }
    maven { url 'https://maven.fabric.io/public' }
  }
  dependencies {
    classpath "com.android.tools.build:gradle:${pluginVersion.gradle}"
    classpath pluginDependencies.kotlin
    classpath pluginDependencies.coveralls
    classpath pluginDependencies.errorprone
    classpath pluginDependencies.dependencyUpdates
    classpath pluginDependencies.jacoco
    classpath pluginDependencies.playPublisher
    classpath pluginDependencies.googleServices
    classpath pluginDependencies.crashlytics
    classpath pluginDependencies.license
    classpath pluginDependencies.mapboxSdkVersions
    classpath pluginDependencies.mavenPublish
    classpath pluginDependencies.bintray
    classpath pluginDependencies.artifactory
    classpath pluginDependencies.dokka
    classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.0-beta01"
  }
}

task testReport(type: TestReport, group: 'Build') {
  description = 'Generates an aggregate test report'
  destinationDir = file("${buildDir}/reports/allTests")
}

allprojects {
  repositories {
    google()
    mavenCentral()
    jcenter()
    maven { url 'https://plugins.gradle.org/m2' }
    maven {
      url 'https://api.mapbox.com/downloads/v1/navigation/android/maven'
      authentication {
        basic(BasicAuthentication)
      }
      credentials {
        username = project.properties['MAPBOX_USER'] ?: ""
        password = project.properties['MAPBOX_TOKEN'] ?: ""
      }
    }
    maven { url 'https://mapbox.bintray.com/mapbox' }
    maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local/' }
  }

  group = GROUP
  version = VERSION_NAME
}

subprojects {
  apply plugin: 'idea'
  apply plugin: 'net.ltgt.errorprone'
  apply from: "${rootDir}/gradle/dependencies.gradle"

  dependencies {
    errorprone dependenciesList.errorprone
  }

  plugins.withId('org.jetbrains.kotlin.jvm') {
    compileKotlin {
      kotlinOptions {
        jvmTarget = "1.8"
      }
    }
  }
}

task clean(type: Delete) {
  delete rootProject.buildDir
}

```

**Comment by abhishek1508** [comment]
@KayHung Looking at the `app/build.gradle`, I don't see the dependency on Navigation SDK `1.0.0-rc.1`. I see that you have added the dependency `implementation project(':libandroid-navigation-ui')`. This is not the right way to add a dependency. As stated in the documentation, you should add the navigation SDK dependency as `implementation 'com.mapbox.navigation:core:1.0.0-rc.1'`

**Comment by KayHung** [comment]
@abhishek1508 
This works, thanks for your help!

**Comment by karanveer0802** [comment]
@abhishek1508  I am aslo facing the same issue as @KayHung  .. i have also changes the dependency still facing error:-
ERROR: Unable to resolve dependency for ':carbon@debug/compileClasspath': Could not resolve com.mapbox.maps:android:10.0.0-alpha.5 .. Not able to run the project

**Comment by innodeltech** [comment]
I am also facing the same issue.
A problem occurred configuring root project 'mapbox-navigation'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.mapbox.gradle.plugins:sdk-registry:0.4.0.
     Required by:
         project :

**Comment by zenyagami** [comment]
same problem i uses several keys with `Download` scope and i receive 
```
could not resolve com.mapbox.gradle.plugins:sdk-registry:0.4.0.
```
im trying latest beta v2 (beta 8)

**Comment by otutuchristopher97** [comment]
Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/access-token/0.4.0/access-token-0.4.0.pom'. Received status code 403 from server: Forbidden

**Comment by shubham1295-droid** [comment]
Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 401 from server: Unauthorized
