### ISSUE TITLE
The route is updated after blinking

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#2578]
**Mapbox Navigation SDK version:** 1.0.0

This is most likely a duplicate issue somewhere. But I have a setup that makes the MapRouteLine blink every time you render it. 

### Steps to trigger behavior

 1. Call [NavigationMapboxMap.drawRoutes](https://github.com/mapbox/mapbox-navigation-android/blob/2a08512a2c7db60609cf6b5672a39a223defca31/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/map/NavigationMapboxMap.java#L362-L364) whenever onRouteProgress is updated

### Expected behavior
The route is updated without blinking

### Actual behavior
The route is updated after blinking

![output](https://user-images.githubusercontent.com/3021882/76480082-ee40f700-63ca-11ea-940b-e6cacc442bb5.gif)

**Comment by kmadsen** [comment]
cc: @RingerJK last changes were the port over https://github.com/mapbox/mapbox-navigation-android/pull/2503

**Comment by kmadsen** [comment]
Related https://github.com/mapbox/mapbox-navigation-android/issues/2473

**Comment by RingerJK** [comment]
@kmadsen I'll take it, thanks to ping me 🙇

**Comment by Guardiola31337** [comment]
@abhishek1508 @cafesilencio could we check if this was already addressed?

**Comment by cafesilencio** [comment]
I don't think this is still an issue but I will do some further testing.

**Comment by cafesilencio** [comment]
NavigationMapboxMap.drawRoutes will always clear the route layer and always has. That will cause a blinking because first the layers are cleared and then a new feature collection is applied. This behavior was the same in the legacy version.  NavigationMapboxMap.drawRoutes shouldn't be called onRouteProgress. The MaprouteProgressChangeListener will take care of drawing a new route on a progress update if the route has changed.

**Comment by kmadsen** [comment]
> NavigationMapboxMap.drawRoutes shouldn't be called onRouteProgress. The MaprouteProgressChangeListener will take care of drawing a new route on a progress update if the route has changed.

Ok nice, what is the public interface to update routes then? I see we are still calling onNewRouteProgress but is that needed? do we only need addProgressChangeListener?

For example, does this callback need to be registered?
https://github.com/mapbox/mapbox-navigation-android/blob/058459d9336a2bd454394ba48732d5e4eb5af921/examples/src/main/java/com/mapbox/navigation/examples/core/SimpleMapboxNavigationKt.kt#L264

**Comment by kmadsen** [comment]
Closing this issue thanks for [following up](https://github.com/mapbox/mapbox-navigation-android/issues/2578#issuecomment-639172581) @cafesilencio !

Have a question on the public interfaces considering MapRouteProgressChangeListener is internal. Also can you let us know if the examples need to be updated?

**Comment by cafesilencio** [comment]
@kmadsen I think the examples have been updated as needed with the recent work to demonstrate device rotation.
