### ISSUE TITLE
Missing upcoming maneuver arrows

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2845]
When testing the `examples` test app noticed that we're not drawing the upcoming maneuver arrows anymore 👀 

| Legacy | `1.0` UI SDK |
| -- | --- |
| ![upcoming_maneuver_arrow_legacy_navigation_view](https://user-images.githubusercontent.com/1668582/80431056-65204980-88be-11ea-99d9-a2c57dc7826c.gif) | ![upcoming_maneuver_arrow_1_0_navigation_view](https://user-images.githubusercontent.com/1668582/80431062-694c6700-88be-11ea-954a-8723128b7d4d.gif) |

This is the `NavigationView` (`Navigation UI SDK`) but it's also reproducible in the examples that use the `NavigationMapboxMap` / `NavigationMapRoute` (`Navigation Core SDK`). What did it change recently? It sounds like a regression, would swear this was working 🤔 

cc @JunDai @abhishek1508 @cafesilencio

**Comment by Guardiola31337** [comment]
It seems OP was fixed in https://github.com/mapbox/mapbox-navigation-android/pull/2849 but noticed something else 👀 

![simple_mapbox_navigation_kt_session_stopped](https://user-images.githubusercontent.com/1668582/80654211-c45e9500-8a49-11ea-802d-824a4c65adbc.png)

The upcoming maneuver arrows are still visible when the session is stopped and the route line keeps the vanishing state. Should we restore it? Remove it?

cc @cafesilencio @abhishek1508

**Comment by cafesilencio** [comment]
I believe this issue has been resolved.

![20200501_155150](https://user-images.githubusercontent.com/2249818/80847265-df551480-8bc3-11ea-8781-6811dac15758.gif)

**Comment by Guardiola31337** [comment]
Going to re-open this as the upcoming maneuvers arrows are still missing in the Drop-in UI 👀 

`NavigationViewActivity`

![navigation_view_activity_missing_maneuver_arrows](https://user-images.githubusercontent.com/1668582/81199644-f1063580-8f90-11ea-94b9-b40635bcb30a.gif)

`BuildingFootprintHighlightActivityKt`

![building_highlight_footprint_activity_missing_maneuver_arrows](https://user-images.githubusercontent.com/1668582/81199695-03806f00-8f91-11ea-82bd-f93e35d3a3fe.gif)

`BuildingExtrusionActivity`

![building_extrusion_activity_missing_maneuver_arrows](https://user-images.githubusercontent.com/1668582/81199753-15faa880-8f91-11ea-88b0-554e3e80ca40.gif)

`CustomPuckActivity`

![custom_puck_activity_missing_maneuver_arrows](https://user-images.githubusercontent.com/1668582/81199824-2e6ac300-8f91-11ea-9f2b-9b4bebc958da.gif)

`CustomCameraActivity`

![custom_camera_activity_missing_maneuver_arrows](https://user-images.githubusercontent.com/1668582/81199872-39bdee80-8f91-11ea-98b4-9c796a322fd2.gif)

Note the weird camera behavior in `BuildingFootprintHighlightActivityKt` and `CustomPuckActivity`.

cc @cafesilencio @kmadsen

**Comment by cafesilencio** [comment]
This is a side effect of making the vanishing route line optional. It's turned off by default. The update for the arrows is in the same block of code. Good catch.
