### ISSUE TITLE
CI will pass when tests fail

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#3409]
Creating from this comment https://github.com/mapbox/mapbox-navigation-android/pull/3408#issuecomment-669476009

This passed CI when a test couldn't compile https://github.com/mapbox/mapbox-navigation-android/pull/3395

"It fails but make `core-unit-tests` keeps going without exiting and making the build ❌"

To verify the CI fix, you could revert the changes from https://github.com/mapbox/mapbox-navigation-android/pull/3408, create a pull request, and CI should fail. 

cc: @Guardiola31337

**Comment by Guardiola31337** [comment]
As mentioned https://github.com/mapbox/mapbox-navigation-android/pull/3408#issuecomment-669475514 problem is `Makefile` command. We should fix it so if any of the builds fails short circuits the rest and returns ❌

I believe currently it's the last build the one that is taken to account to report ✅ or ❌ 

cc @LukasPaczos @abhishek1508

**Comment by kmadsen** [comment]
Well master is still broken because of this https://circleci.com/gh/mapbox/mobile-metrics/12302?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
