### ISSUE TITLE
Navigation Launcher Issues

### ISSUE THREAD

**Issue by chean5143** [mapbox/mapbox-navigation-android#503]
When I try to call **NavigationLauncher.startNavigation(this, route, null, true)**
it show the error below:

11-15 21:18:38.295 1764-1764/com.example.chean.atsc E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.example.chean.atsc, PID: 1764
                                                                      java.lang.RuntimeException: Unable to destroy activity {com.example.chean.atsc/com.mapbox.services.android.navigation.ui.v5.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.destroy()' on a null object reference
                                                                          at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4195)
                                                                          at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4213)
                                                                          at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4431)
                                                                          at android.app.ActivityThread.access$1000(ActivityThread.java:177)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5938)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.destroy()' on a null object reference
                                                                          at com.mapbox.mapboxsdk.maps.MapView.onDestroy(MapView.java:410)
                                                                          at com.mapbox.services.android.navigation.ui.v5.NavigationView.onDestroy(NavigationView.java:125)
                                                                          at com.mapbox.services.android.navigation.ui.v5.NavigationActivity.onDestroy(NavigationActivity.java:59)
                                                                          at android.app.Activity.performDestroy(Activity.java:6524)
                                                                          at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
                                                                          at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4173)
                                                                          at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4213) 
                                                                          at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4431) 
                                                                          at android.app.ActivityThread.access$1000(ActivityThread.java:177) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:145) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5938) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)

**Comment by AnvayMTL** [comment]
Any update ?

**Comment by danesfeder** [comment]
This NPE was in the Maps SDK and was fixed in the latest `5.2.0` update.  This is now available in the latest navigation UI `0.7.1-SNAPSHOT` and we are working hard to release a stable `0.7.1` ASAP.  Stay tuned for this update

**Comment by lim996** [comment]
I included the 0.7.1-SNAPSHOT but I still get the same error.. any update?

**Comment by MehdiFal** [comment]
Using `0.7.1-SNAPSHOT` and I still get this exception as well. Any workaround?

**Comment by danesfeder** [comment]
@tobrun It looks like in certain initialization scenarios, https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L419 --> `nativeMapView` is null.  I think this may be when we start up the UI and immediately re-create it to go into "dark mode"

**Comment by lim996** [comment]
Is dark mode the style of the map after the sunset? Because I used navigation yesterday evening and it crashed, but now (in the morning) it’s working... how can I fix it?

**Comment by Halpph** [comment]
Same probem here, it crashes in the night navigation

**Comment by tobrun** [comment]
Thank you for looking into this @danesfeder, you use-case seems to be valid. One question though, is your day/night theming setup with the appcompat theming?

**Comment by danesfeder** [comment]
Was fixed in the Maps SDK with https://github.com/mapbox/mapbox-gl-native/pull/10589, which is now available in the `0.7.1` release.  Thanks for your help with this @tobrun
