### ISSUE TITLE
Android: LostLocation DeadObjectException

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#522]
I'm Now Using The Following Gradle Setup
```
    // Mapbox Maps SDK
    implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
    implementation "com.mapzen.android:lost:3.0.4"
```

I'm recieving the below error.

**Error**
```
11-21 12:39:58.579 10984-10984/uk.co.ainscough.routeinfo:lost E/FusedLocationProviderServiceDelegate: Error occurred trying to report a new Location
                                                                                                      android.os.DeadObjectException
                                                                                                          at android.os.BinderProxy.transact(Native Method)
                                                                                                          at com.mapzen.android.lost.internal.IFusedLocationProviderCallback$Stub$Proxy.onLocationChanged(IFusedLocationProviderCallback.java:129)
                                                                                                          at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java:95)
                                                                                                          at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:196)
                                                                                                          at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:263)
                                                                                                          at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:196)
                                                                                                          at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:219)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:4895)
                                                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                                                          at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Danny-James** [comment]
I Also Keep Getting The Following Error.

```
11-21 11:51:16.137 21225-21225/uk.co.ainscough.routeinfo I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.services.android.telemetry.location.GoogleLocationEngine>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationListener;
11-21 11:51:16.137 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
11-21 11:51:16.137 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void uk.co.ainscough.routeinfo.ActivityNavigationMap.onCreate(android.os.Bundle) (ActivityNavigationMap.java:125)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7000)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6991)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.os.Looper.loop() (Looper.java:164)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationListener" on path: DexPathList[[zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/base.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_dependencies_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_0_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_1_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_2_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_3_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_4_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_5_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_6_apk.apk", zip file
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void uk.co.ainscough.routeinfo.ActivityNavigationMap.onCreate(android.os.Bundle) (ActivityNavigationMap.java:125)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7000)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6991)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.os.Looper.loop() (Looper.java:164)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.services.android.telemetry.location.GoogleLocationEngine>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationListener;
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void uk.co.ainscough.routeinfo.ActivityNavigationMap.onCreate(android.os.Bundle) (ActivityNavigationMap.java:125)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7000)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6991)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.os.Looper.loop() (Looper.java:164)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationListener" on path: DexPathList[[zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/base.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_dependencies_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_0_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_1_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_2_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_3_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_4_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_5_apk.apk", zip file "/data/app/uk.co.ainscough.routeinfo-ciSCdjY95lLmCf9fvsIOYQ==/split_lib_slice_6_apk.apk", zip file
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void uk.co.ainscough.routeinfo.ActivityNavigationMap.onCreate(android.os.Bundle) (ActivityNavigationMap.java:125)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7000)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6991)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.os.Looper.loop() (Looper.java:164)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
11-21 11:51:16.138 21225-21225/uk.co.ainscough.routeinfo I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)

```

**Comment by danesfeder** [comment]
@Danny-James Yeah sorry about this, `5.2.0` of the Maps SDK made the location code we provide completely optional.  This should now be fixed in the `0.7.1-SNAPSHOT`.  If you are using the navigation UI, you would only need the following to include everything you have listed above:
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') {
    transitive = true
}
```

We are working hard to release `0.7.1` stable ASAP.  Thanks for working with us on figuring this out!

**Comment by Danny-James** [comment]
@danesfeder Just to confirm i will only require the following gradle 

```
    // Mapbox Maps SDK
    implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar') {
        transitive = true
    }
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') {
    transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
```

**Comment by Danny-James** [comment]
@danesfeder i'm now using the above Gradle, Android O 8.0.1 is now working Fine, I'm still getting the below error on Android 4.1.2 Motorol TC55.

```
11-22 15:42:43.949 4543-5312/uk.co.ainscough.routeinfo A/libc: @@@ ABORTING: HEAP MEMORY CORRUPTION IN dlmalloc addr=0x5e17dbf8
11-22 15:42:43.949 4543-5312/uk.co.ainscough.routeinfo A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 5312 (Worker 2)
11-22 15:42:44.049 167-167/? I/DEBUG: pid: 4543, tid: 5312, name: Worker 2  >>> uk.co.ainscough.routeinfo <<<
11-22 15:42:44.149 167-167/? I/DEBUG:     #03  pc 00320259  /data/app-lib/uk.co.ainscough.routeinfo-2/libmapbox-gl.so
11-22 15:42:44.149 167-167/? I/DEBUG:          63847bc4  6290125d  /data/app-lib/uk.co.ainscough.routeinfo-2/libmapbox-gl.so
11-22 15:42:44.820 5285-5285/uk.co.ainscough.routeinfo:lost E/FusedLocationProviderServiceDelegate: Error occurred trying to report a new Location
                                                                                                    android.os.DeadObjectException
                                                                                                        at android.os.BinderProxy.transact(Native Method)
                                                                                                        at com.mapzen.android.lost.internal.IFusedLocationProviderCallback$Stub$Proxy.onLocationChanged(IFusedLocationProviderCallback.java:129)
                                                                                                        at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java:95)
                                                                                                        at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:196)
                                                                                                        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:263)
                                                                                                        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:196)
                                                                                                        at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:219)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4895)
                                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                                                    
                                                                                                    
                                                                                                    [ 11-22 15:42:44.820   562:  601 E/         ]
                                                                                                    restore_sensor_profile: device is not in VC
                                                                                                    
                                                                                                    [ 11-22 15:42:44.820   562:  601 E/         ]
                                                                                                    restore_sensor_profile: profile is /data/local/tmp/profile_calib_m
                                                                                                    
                                                                                                    [ 11-22 15:42:44.820   562:  601 E/         ]
                                                                                                    invalid content in file: /data/local/tmp/profile_calib_m
```

**Comment by danesfeder** [comment]
@Danny-James Can you try again with this gradle setup?
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') {
    transitive = true
}
```

**Comment by Danny-James** [comment]
@danesfeder, I require the MapBox SDK, for one of my activities which shows a MapView and an overview of the Route.

Are you saying i don't need to include the dependency below?

```
implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar') {
        transitive = true
    }
```

**Comment by danesfeder** [comment]
@Danny-James yeah we include the Maps SDK `5.2.0` in the `navigation-ui` dependency: https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/build.gradle#L37

So your code should still compile fine and you'll still be able to use `MapView` throughout your project

**Comment by Danny-James** [comment]
@danesfeder Do i need to exclude the following:

```
     exclude module: 'lost' 
     exclude module: 'mapbox-java-geojson' 
     exclude module: 'mapbox-android-telemetry' 
```

**Comment by danesfeder** [comment]
@Danny-James we do this in the `build.gradle` for `navigation-ui` to ensure there aren't other dependency conflicts and everything is properly setup.  You won't need to do that in your gradle file.

**Comment by Danny-James** [comment]
@danesfeder Cheers, will give this a try tomorrow and report back.

**Comment by Danny-James** [comment]
@danesfeder Still getting the error mate.

**Comment by danesfeder** [comment]
@Guardiola31337 With the update to LOST `3.0.4` this exception occurs after a different exception from something else and isn't actually fatal correct?

**Comment by danesfeder** [comment]
@Danny-James are you still getting this?  You may need to reset your gradle cache to make sure there is no longer a conflict here.

**Comment by Danny-James** [comment]
@danesfeder Will Check This Now.

**Comment by Danny-James** [comment]
@danesfeder I'm unable to check as I'm getting the unable to resolve errors on the following imports.

```java
import com.mapbox.directions.v5.DirectionsCriteria;
import com.mapbox.directions.v5.models.DirectionsResponse;
import com.mapbox.directions.v5.models.DirectionsRoute;
```

```
Error:(29, 32) error: package com.mapbox.directions.v5 does not exist
Error:(30, 39) error: package com.mapbox.directions.v5.models does not exist
Error:(31, 39) error: package com.mapbox.directions.v5.models does not exist
```

**Comment by Danny-James** [comment]
@danesfeder I Deleted The Cache And Was Still Getting The Error Shown Above, I Added `changing = true` to my gradle and it has now pulled through the latest SNAPSHOT - Will see if i still get the issue.

**Comment by Danny-James** [comment]
I'm Not Getting The Original Error Reported On Google Pixel Device,  However, I'm Unable To Test on Android 4.1.2 Device Due To Crash When Starting Navigation UI.

**See Full Logcat** 
[LogCat_Export_GitHub_522.txt](https://github.com/mapbox/mapbox-navigation-android/files/1536158/LogCat_Export_GitHub_522.txt)

Crash Is Around: `Line 151 (12-06 16:58:28.199)`

**Comment by danesfeder** [comment]
Hey @Danny-James this isn't specific to the Android crash you're seeing on your 4.1.2 Motorola - this issue was part of a transition we made to our new Java library.
