### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by sarveshAgrawal** [mapbox/mapbox-navigation-android#970]
ERROR 1.4.1java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
	at com.mapbox.android.telemetry.TelemetryUtils.obtainApplicationState(TelemetryUtils.java:100)
	at com.mapbox.android.telemetry.LocationEvent.<init>(LocationEvent.java:44)
	at com.mapbox.android.telemetry.LocationMapper.createLocationEvent(LocationMapper.java:32)
	at com.mapbox.android.telemetry.LocationMapper.from(LocationMapper.java:18)
	at com.mapbox.android.telemetry.LocationReceiver.sendEvent(LocationReceiver.java:47)
	at com.mapbox.android.telemetry.LocationReceiver.onReceive(LocationReceiver.java:26)
	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5319)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Android API:**
**Mapbox Navigation SDK version:**

 // MapBox
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.1@aar') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.13.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0') {
        transitive = true
    }

### Steps to trigger behavior

 1. open navigation screen after some time it automatically crashes.
 2.
 3.

### code.

  Mapbox.getInstance(getApplicationContext(), getString(R.string.access_token));
        setContentView(R.layout.activity_map_navigation);
 client_lat = Double.parseDouble(getIntent().getStringExtra("emergency_latitude"));
        client_long = Double.parseDouble(getIntent().getStringExtra("emergency_longitude"));

        tracker = new GPSTracker(getApplicationContext());
        if (tracker.canGetLocation()) {
            current_long = tracker.getLongitude();
            current_lat = tracker.getLatitude();
        }

        origin = Point.fromLngLat(current_long, current_lat);
        destination = Point.fromLngLat(client_long, client_lat);

        navigationView = findViewById(R.id.navigationView);
        navigationView.onCreate(savedInstanceState);
        navigationView.initialize(
                new OnNavigationReadyCallback() {
            @Override
            public void onNavigationReady() {

                NavigationViewOptions.Builder options = NavigationViewOptions.builder();
                options.origin(origin);
                options.destination(destination);
                options.shouldSimulateRoute(false);

                navigationView.startNavigation(options.build());
            }
        });

**Comment by Guardiola31337** [comment]
Hey @sarveshAgrawal 👋 Thanks for reaching out and report your issue.

Could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup? Do you have some more information on used device? If there is any sample or pseudo code you can provide, that would be really helpful because without having additional information, I'm unable to reproduce.

BTW, we released version [`6.1.3`](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v6.1.3) of the Maps SDK yesterday which solves a bunch of issues and bumps the events library to [`3.1.2`](https://github.com/mapbox/mapbox-events-android/releases/tag/telem-3.1.2). Could you please retest this using `6.1.3` and report back if it's still an issue?

cc @electrostat

**Comment by sarveshAgrawal** [comment]
I have Upgrade the version to 6.1.3

My Tester is again testing the Navigation Screen and MapView screen in the map box app.

Device Sony Experia, Version 5.0, Lolipop
Lenovo , version 6.0 and 6.0.1 , Marshmello 
and Mi phone version 7.1.2.

**Comment by Guardiola31337** [comment]
@sarveshAgrawal 
> I have Upgrade the version to 6.1.3

Are you still 👀 the crash after upgrading?

Your issue was fixed in https://github.com/mapbox/mapbox-events-android/pull/144 and it's available since version `6.1.2` of the Maps SDK (`3.1.1` version of the Events library) 👀 https://github.com/mapbox/mapbox-events-android/blob/502cdd7d89b7a6027cf113a8f9caaa5eb3d1e551/libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java#L98 https://github.com/mapbox/mapbox-events-android/blob/502cdd7d89b7a6027cf113a8f9caaa5eb3d1e551/libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java#L245-L249

I've tested the same configuration in the test app and also in a plain new project on different devices and I wasn't able to reproduce the issue described in OP.

As explained, if you update to `6.1.3` you shouldn't run into that crash anymore. Could you confirm please?

**Comment by danesfeder** [comment]
@sarveshAgrawal going to go ahead and close this as our currently library includes mapbox/mapbox-events-android#144 - if you find the issue persists, please feel free to re-open and we will continue to dig on this issue.  Thanks for bringing this to our attention! 

cc @electrostat

**Comment by kontownik** [comment]
it isn't fixed https://github.com/Mapwize/mapwize-ui-android/issues/20
